# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner.ui'
#
# Created: Mon Nov 12 11:25:21 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(840, 906)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(10, 10))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.sdpMainWindow = QtGui.QWidget(MainWindow)
        self.sdpMainWindow.setObjectName(_fromUtf8("sdpMainWindow"))
        self.verticalLayout = QtGui.QVBoxLayout(self.sdpMainWindow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pickingModeCombo = QtGui.QComboBox(self.sdpMainWindow)
        self.pickingModeCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.pickingModeCombo.setObjectName(_fromUtf8("pickingModeCombo"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Gnome-Zoom-Fit-Best-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pickingModeCombo.addItem(icon1, _fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Move-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pickingModeCombo.addItem(icon2, _fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Remove-32 (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pickingModeCombo.addItem(icon3, _fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon_clipboard.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pickingModeCombo.addItem(icon4, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.pickingModeCombo)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.mainPlot = Qwt5.QwtPlot(self.sdpMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPlot.sizePolicy().hasHeightForWidth())
        self.mainPlot.setSizePolicy(sizePolicy)
        self.mainPlot.setObjectName(_fromUtf8("mainPlot"))
        self.verticalLayout_11.addWidget(self.mainPlot)
        self.tabWidget = QtGui.QTabWidget(self.sdpMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.dateCombo = QtGui.QComboBox(self.groupBox_3)
        self.dateCombo.setObjectName(_fromUtf8("dateCombo"))
        self.verticalLayout_5.addWidget(self.dateCombo)
        self.datasetList = QtGui.QListWidget(self.groupBox_3)
        self.datasetList.setObjectName(_fromUtf8("datasetList"))
        self.verticalLayout_5.addWidget(self.datasetList)
        self.avgStd = QtGui.QRadioButton(self.groupBox_3)
        self.avgStd.setChecked(True)
        self.avgStd.setObjectName(_fromUtf8("avgStd"))
        self.verticalLayout_5.addWidget(self.avgStd)
        self.avgStdSqrtN = QtGui.QRadioButton(self.groupBox_3)
        self.avgStdSqrtN.setObjectName(_fromUtf8("avgStdSqrtN"))
        self.verticalLayout_5.addWidget(self.avgStdSqrtN)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.axesGroup = QtGui.QGroupBox(self.tab)
        self.axesGroup.setObjectName(_fromUtf8("axesGroup"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.axesGroup)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.axesTbl = QtGui.QTableWidget(self.axesGroup)
        self.axesTbl.setGridStyle(QtCore.Qt.NoPen)
        self.axesTbl.setColumnCount(4)
        self.axesTbl.setObjectName(_fromUtf8("axesTbl"))
        self.axesTbl.setColumnCount(4)
        self.axesTbl.setRowCount(0)
        self.axesTbl.horizontalHeader().setVisible(False)
        self.axesTbl.horizontalHeader().setDefaultSectionSize(80)
        self.axesTbl.horizontalHeader().setMinimumSectionSize(10)
        self.axesTbl.verticalHeader().setVisible(False)
        self.axesTbl.verticalHeader().setDefaultSectionSize(30)
        self.axesTbl.verticalHeader().setMinimumSectionSize(10)
        self.horizontalLayout_5.addWidget(self.axesTbl)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.oldAxesButton = QtGui.QPushButton(self.axesGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldAxesButton.sizePolicy().hasHeightForWidth())
        self.oldAxesButton.setSizePolicy(sizePolicy)
        self.oldAxesButton.setMinimumSize(QtCore.QSize(24, 24))
        self.oldAxesButton.setMaximumSize(QtCore.QSize(24, 24))
        self.oldAxesButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.oldAxesButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Actions-view-refresh-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oldAxesButton.setIcon(icon5)
        self.oldAxesButton.setIconSize(QtCore.QSize(16, 16))
        self.oldAxesButton.setAutoRepeat(False)
        self.oldAxesButton.setAutoExclusive(False)
        self.oldAxesButton.setObjectName(_fromUtf8("oldAxesButton"))
        self.verticalLayout_7.addWidget(self.oldAxesButton)
        self.addAxesButton = QtGui.QPushButton(self.axesGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAxesButton.sizePolicy().hasHeightForWidth())
        self.addAxesButton.setSizePolicy(sizePolicy)
        self.addAxesButton.setMinimumSize(QtCore.QSize(24, 24))
        self.addAxesButton.setMaximumSize(QtCore.QSize(24, 24))
        self.addAxesButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addAxesButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Add-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAxesButton.setIcon(icon6)
        self.addAxesButton.setIconSize(QtCore.QSize(16, 16))
        self.addAxesButton.setAutoRepeat(False)
        self.addAxesButton.setAutoExclusive(False)
        self.addAxesButton.setObjectName(_fromUtf8("addAxesButton"))
        self.verticalLayout_7.addWidget(self.addAxesButton)
        self.removeAxesButton = QtGui.QPushButton(self.axesGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeAxesButton.sizePolicy().hasHeightForWidth())
        self.removeAxesButton.setSizePolicy(sizePolicy)
        self.removeAxesButton.setMinimumSize(QtCore.QSize(24, 24))
        self.removeAxesButton.setMaximumSize(QtCore.QSize(24, 24))
        self.removeAxesButton.setBaseSize(QtCore.QSize(20, 0))
        self.removeAxesButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Remove-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeAxesButton.setIcon(icon7)
        self.removeAxesButton.setObjectName(_fromUtf8("removeAxesButton"))
        self.verticalLayout_7.addWidget(self.removeAxesButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addWidget(self.axesGroup)
        self.groupBox = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.conditionTbl = QtGui.QTableWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conditionTbl.sizePolicy().hasHeightForWidth())
        self.conditionTbl.setSizePolicy(sizePolicy)
        self.conditionTbl.setRowCount(1)
        self.conditionTbl.setColumnCount(3)
        self.conditionTbl.setObjectName(_fromUtf8("conditionTbl"))
        self.conditionTbl.setColumnCount(3)
        self.conditionTbl.setRowCount(1)
        self.conditionTbl.horizontalHeader().setVisible(False)
        self.conditionTbl.horizontalHeader().setCascadingSectionResizes(False)
        self.conditionTbl.horizontalHeader().setDefaultSectionSize(80)
        self.conditionTbl.horizontalHeader().setMinimumSectionSize(10)
        self.conditionTbl.horizontalHeader().setStretchLastSection(True)
        self.conditionTbl.verticalHeader().setVisible(False)
        self.conditionTbl.verticalHeader().setMinimumSectionSize(10)
        self.horizontalLayout_3.addWidget(self.conditionTbl)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.disableConditionsButton = QtGui.QPushButton(self.groupBox)
        self.disableConditionsButton.setMinimumSize(QtCore.QSize(20, 20))
        self.disableConditionsButton.setMaximumSize(QtCore.QSize(24, 24))
        self.disableConditionsButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Actions-system-switch-user-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disableConditionsButton.setIcon(icon8)
        self.disableConditionsButton.setCheckable(True)
        self.disableConditionsButton.setObjectName(_fromUtf8("disableConditionsButton"))
        self.verticalLayout_2.addWidget(self.disableConditionsButton)
        self.addConditionButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addConditionButton.sizePolicy().hasHeightForWidth())
        self.addConditionButton.setSizePolicy(sizePolicy)
        self.addConditionButton.setMinimumSize(QtCore.QSize(24, 24))
        self.addConditionButton.setMaximumSize(QtCore.QSize(24, 16777215))
        self.addConditionButton.setBaseSize(QtCore.QSize(20, 0))
        self.addConditionButton.setText(_fromUtf8(""))
        self.addConditionButton.setIcon(icon6)
        self.addConditionButton.setObjectName(_fromUtf8("addConditionButton"))
        self.verticalLayout_2.addWidget(self.addConditionButton)
        self.removeConditionButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeConditionButton.sizePolicy().hasHeightForWidth())
        self.removeConditionButton.setSizePolicy(sizePolicy)
        self.removeConditionButton.setMinimumSize(QtCore.QSize(24, 24))
        self.removeConditionButton.setMaximumSize(QtCore.QSize(24, 24))
        self.removeConditionButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.removeConditionButton.setBaseSize(QtCore.QSize(32, 32))
        self.removeConditionButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.removeConditionButton.setText(_fromUtf8(""))
        self.removeConditionButton.setIcon(icon7)
        self.removeConditionButton.setIconSize(QtCore.QSize(16, 16))
        self.removeConditionButton.setAutoDefault(False)
        self.removeConditionButton.setObjectName(_fromUtf8("removeConditionButton"))
        self.verticalLayout_2.addWidget(self.removeConditionButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_10.addWidget(self.groupBox)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_active-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon9, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_13.addWidget(self.label_3)
        self.fitTypeCombo = QtGui.QComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitTypeCombo.sizePolicy().hasHeightForWidth())
        self.fitTypeCombo.setSizePolicy(sizePolicy)
        self.fitTypeCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.fitTypeCombo.setMaxVisibleItems(20)
        self.fitTypeCombo.setObjectName(_fromUtf8("fitTypeCombo"))
        self.verticalLayout_13.addWidget(self.fitTypeCombo)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.fitFromSpin = QtGui.QDoubleSpinBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitFromSpin.sizePolicy().hasHeightForWidth())
        self.fitFromSpin.setSizePolicy(sizePolicy)
        self.fitFromSpin.setDecimals(6)
        self.fitFromSpin.setMinimum(-16777215.0)
        self.fitFromSpin.setMaximum(16777215.0)
        self.fitFromSpin.setProperty(_fromUtf8("value"), 0.0)
        self.fitFromSpin.setObjectName(_fromUtf8("fitFromSpin"))
        self.horizontalLayout_2.addWidget(self.fitFromSpin)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.fitToSpin = QtGui.QDoubleSpinBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitToSpin.sizePolicy().hasHeightForWidth())
        self.fitToSpin.setSizePolicy(sizePolicy)
        self.fitToSpin.setDecimals(6)
        self.fitToSpin.setMinimum(-16777215.0)
        self.fitToSpin.setMaximum(16777215.0)
        self.fitToSpin.setSingleStep(1.0)
        self.fitToSpin.setObjectName(_fromUtf8("fitToSpin"))
        self.horizontalLayout.addWidget(self.fitToSpin)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.updateFitRangeButton = QtGui.QPushButton(self.tab_2)
        self.updateFitRangeButton.setIcon(icon5)
        self.updateFitRangeButton.setObjectName(_fromUtf8("updateFitRangeButton"))
        self.verticalLayout_13.addWidget(self.updateFitRangeButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.fittingParametersGroup = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fittingParametersGroup.sizePolicy().hasHeightForWidth())
        self.fittingParametersGroup.setSizePolicy(sizePolicy)
        self.fittingParametersGroup.setObjectName(_fromUtf8("fittingParametersGroup"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.fittingParametersGroup)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.parametersTbl = QtGui.QTableWidget(self.fittingParametersGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parametersTbl.sizePolicy().hasHeightForWidth())
        self.parametersTbl.setSizePolicy(sizePolicy)
        self.parametersTbl.setMinimumSize(QtCore.QSize(0, 0))
        self.parametersTbl.setObjectName(_fromUtf8("parametersTbl"))
        self.parametersTbl.setColumnCount(0)
        self.parametersTbl.setRowCount(0)
        self.parametersTbl.horizontalHeader().setDefaultSectionSize(90)
        self.parametersTbl.horizontalHeader().setStretchLastSection(True)
        self.parametersTbl.verticalHeader().setDefaultSectionSize(35)
        self.verticalLayout_8.addWidget(self.parametersTbl)
        self.fillAutoFitParametersButton = QtGui.QPushButton(self.fittingParametersGroup)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/undo_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fillAutoFitParametersButton.setIcon(icon10)
        self.fillAutoFitParametersButton.setObjectName(_fromUtf8("fillAutoFitParametersButton"))
        self.verticalLayout_8.addWidget(self.fillAutoFitParametersButton)
        self.horizontalLayout_11.addWidget(self.fittingParametersGroup)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textEdit = QtGui.QTextEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textEdit.setFrameShadow(QtGui.QFrame.Sunken)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Chart-Line-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon11, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.transformTypeCombo = QtGui.QComboBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformTypeCombo.sizePolicy().hasHeightForWidth())
        self.transformTypeCombo.setSizePolicy(sizePolicy)
        self.transformTypeCombo.setObjectName(_fromUtf8("transformTypeCombo"))
        self.verticalLayout_4.addWidget(self.transformTypeCombo)
        self.transformInfo = QtGui.QTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformInfo.sizePolicy().hasHeightForWidth())
        self.transformInfo.setSizePolicy(sizePolicy)
        self.transformInfo.setObjectName(_fromUtf8("transformInfo"))
        self.verticalLayout_4.addWidget(self.transformInfo)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        self.transformConstantTbl = QtGui.QTableWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformConstantTbl.sizePolicy().hasHeightForWidth())
        self.transformConstantTbl.setSizePolicy(sizePolicy)
        self.transformConstantTbl.setColumnCount(2)
        self.transformConstantTbl.setObjectName(_fromUtf8("transformConstantTbl"))
        self.transformConstantTbl.setColumnCount(2)
        self.transformConstantTbl.setRowCount(0)
        self.transformConstantTbl.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_12.addWidget(self.transformConstantTbl)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/import-export-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon12, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.xaxisLabel = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xaxisLabel.sizePolicy().hasHeightForWidth())
        self.xaxisLabel.setSizePolicy(sizePolicy)
        self.xaxisLabel.setObjectName(_fromUtf8("xaxisLabel"))
        self.gridLayout.addWidget(self.xaxisLabel, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.yaxisLabel = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yaxisLabel.sizePolicy().hasHeightForWidth())
        self.yaxisLabel.setSizePolicy(sizePolicy)
        self.yaxisLabel.setObjectName(_fromUtf8("yaxisLabel"))
        self.gridLayout.addWidget(self.yaxisLabel, 2, 1, 1, 1)
        self.xaxisUnit = QtGui.QLineEdit(self.groupBox_4)
        self.xaxisUnit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.xaxisUnit.setObjectName(_fromUtf8("xaxisUnit"))
        self.gridLayout.addWidget(self.xaxisUnit, 0, 2, 1, 1)
        self.yaxisUnit = QtGui.QLineEdit(self.groupBox_4)
        self.yaxisUnit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.yaxisUnit.setObjectName(_fromUtf8("yaxisUnit"))
        self.gridLayout.addWidget(self.yaxisUnit, 2, 2, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.resetAxisStyleButton = QtGui.QPushButton(self.groupBox_4)
        self.resetAxisStyleButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.resetAxisStyleButton.setIcon(icon10)
        self.resetAxisStyleButton.setObjectName(_fromUtf8("resetAxisStyleButton"))
        self.horizontalLayout_14.addWidget(self.resetAxisStyleButton)
        self.applyAxisStyleButton = QtGui.QPushButton(self.groupBox_4)
        self.applyAxisStyleButton.setMaximumSize(QtCore.QSize(100, 16777215))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Actions-dialog-ok-apply-icon (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.applyAxisStyleButton.setIcon(icon13)
        self.applyAxisStyleButton.setObjectName(_fromUtf8("applyAxisStyleButton"))
        self.horizontalLayout_14.addWidget(self.applyAxisStyleButton)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem4)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.xrangeMinSpin = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.xrangeMinSpin.setMaximum(1600000000.0)
        self.xrangeMinSpin.setObjectName(_fromUtf8("xrangeMinSpin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.xrangeMinSpin)
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.yrangeMinSpin = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.yrangeMinSpin.setMaximum(1600000000.0)
        self.yrangeMinSpin.setProperty(_fromUtf8("value"), 0.0)
        self.yrangeMinSpin.setObjectName(_fromUtf8("yrangeMinSpin"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.yrangeMinSpin)
        self.xrangeMaxSpin = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.xrangeMaxSpin.setMaximum(1600000000.0)
        self.xrangeMaxSpin.setProperty(_fromUtf8("value"), 1.0)
        self.xrangeMaxSpin.setObjectName(_fromUtf8("xrangeMaxSpin"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.xrangeMaxSpin)
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.yrangeMaxSpin = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.yrangeMaxSpin.setMaximum(1600000000.0)
        self.yrangeMaxSpin.setProperty(_fromUtf8("value"), 1.0)
        self.yrangeMaxSpin.setObjectName(_fromUtf8("yrangeMaxSpin"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.yrangeMaxSpin)
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_13)
        self.verticalLayout_12.addLayout(self.formLayout_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.resetRangeButton = QtGui.QPushButton(self.groupBox_7)
        self.resetRangeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.resetRangeButton.setIcon(icon10)
        self.resetRangeButton.setObjectName(_fromUtf8("resetRangeButton"))
        self.horizontalLayout_13.addWidget(self.resetRangeButton)
        self.updateRangeButton = QtGui.QPushButton(self.groupBox_7)
        self.updateRangeButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.updateRangeButton.setIcon(icon13)
        self.updateRangeButton.setCheckable(True)
        self.updateRangeButton.setChecked(False)
        self.updateRangeButton.setObjectName(_fromUtf8("updateRangeButton"))
        self.horizontalLayout_13.addWidget(self.updateRangeButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem6)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.plotStyleListLinePlot = QtGui.QRadioButton(self.groupBox_5)
        self.plotStyleListLinePlot.setChecked(True)
        self.plotStyleListLinePlot.setObjectName(_fromUtf8("plotStyleListLinePlot"))
        self.gridLayout_2.addWidget(self.plotStyleListLinePlot, 0, 0, 1, 1)
        self.plotStyleListPlot = QtGui.QRadioButton(self.groupBox_5)
        self.plotStyleListPlot.setObjectName(_fromUtf8("plotStyleListPlot"))
        self.gridLayout_2.addWidget(self.plotStyleListPlot, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Utilities-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon14, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.infoRampingEdit = QtGui.QLineEdit(self.groupBox_6)
        self.infoRampingEdit.setMinimumSize(QtCore.QSize(170, 0))
        self.infoRampingEdit.setMaximumSize(QtCore.QSize(170, 16777215))
        self.infoRampingEdit.setObjectName(_fromUtf8("infoRampingEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.infoRampingEdit)
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_10)
        self.infoTempEdit = QtGui.QLineEdit(self.groupBox_6)
        self.infoTempEdit.setMinimumSize(QtCore.QSize(170, 0))
        self.infoTempEdit.setObjectName(_fromUtf8("infoTempEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.infoTempEdit)
        self.infoHoldingEdit = QtGui.QLineEdit(self.groupBox_6)
        self.infoHoldingEdit.setMinimumSize(QtCore.QSize(170, 0))
        self.infoHoldingEdit.setMaximumSize(QtCore.QSize(170, 16777215))
        self.infoHoldingEdit.setObjectName(_fromUtf8("infoHoldingEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.infoHoldingEdit)
        self.infoTrapEdit = QtGui.QLineEdit(self.groupBox_6)
        self.infoTrapEdit.setMinimumSize(QtCore.QSize(170, 0))
        self.infoTrapEdit.setMaximumSize(QtCore.QSize(170, 16777215))
        self.infoTrapEdit.setObjectName(_fromUtf8("infoTrapEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.infoTrapEdit)
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_11)
        self.infoCompressedEdit = QtGui.QLineEdit(self.groupBox_6)
        self.infoCompressedEdit.setMinimumSize(QtCore.QSize(170, 0))
        self.infoCompressedEdit.setMaximumSize(QtCore.QSize(170, 16777215))
        self.infoCompressedEdit.setObjectName(_fromUtf8("infoCompressedEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.infoCompressedEdit)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_12)
        self.calibrationEdit = QtGui.QLineEdit(self.groupBox_6)
        self.calibrationEdit.setMinimumSize(QtCore.QSize(170, 0))
        self.calibrationEdit.setMaximumSize(QtCore.QSize(170, 16777215))
        self.calibrationEdit.setObjectName(_fromUtf8("calibrationEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.calibrationEdit)
        self.horizontalLayout_9.addWidget(self.groupBox_6)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.infoEdit = QtGui.QPlainTextEdit(self.tab_5)
        self.infoEdit.setObjectName(_fromUtf8("infoEdit"))
        self.verticalLayout_6.addWidget(self.infoEdit)
        self.infoCopyEdit = QtGui.QPushButton(self.tab_5)
        self.infoCopyEdit.setObjectName(_fromUtf8("infoCopyEdit"))
        self.verticalLayout_6.addWidget(self.infoCopyEdit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Status-dialog-information-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon15, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.fitDataButton = QtGui.QPushButton(self.sdpMainWindow)
        self.fitDataButton.setIcon(icon11)
        self.fitDataButton.setCheckable(True)
        self.fitDataButton.setObjectName(_fromUtf8("fitDataButton"))
        self.horizontalLayout_6.addWidget(self.fitDataButton)
        self.averageDataButton = QtGui.QPushButton(self.sdpMainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Chart-Curve-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.averageDataButton.setIcon(icon16)
        self.averageDataButton.setCheckable(True)
        self.averageDataButton.setObjectName(_fromUtf8("averageDataButton"))
        self.horizontalLayout_6.addWidget(self.averageDataButton)
        self.transformDataButton = QtGui.QPushButton(self.sdpMainWindow)
        self.transformDataButton.setIcon(icon12)
        self.transformDataButton.setCheckable(True)
        self.transformDataButton.setObjectName(_fromUtf8("transformDataButton"))
        self.horizontalLayout_6.addWidget(self.transformDataButton)
        self.clipboardPlotButton = QtGui.QPushButton(self.sdpMainWindow)
        self.clipboardPlotButton.setIcon(icon4)
        self.clipboardPlotButton.setObjectName(_fromUtf8("clipboardPlotButton"))
        self.horizontalLayout_6.addWidget(self.clipboardPlotButton)
        self.clipboardDataButton = QtGui.QPushButton(self.sdpMainWindow)
        self.clipboardDataButton.setIcon(icon4)
        self.clipboardDataButton.setObjectName(_fromUtf8("clipboardDataButton"))
        self.horizontalLayout_6.addWidget(self.clipboardDataButton)
        self.exportDataButton = QtGui.QPushButton(self.sdpMainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filesaveas-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportDataButton.setIcon(icon17)
        self.exportDataButton.setObjectName(_fromUtf8("exportDataButton"))
        self.horizontalLayout_6.addWidget(self.exportDataButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_11)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_9)
        MainWindow.setCentralWidget(self.sdpMainWindow)
        self.sdpStatusBar = QtGui.QStatusBar(MainWindow)
        self.sdpStatusBar.setObjectName(_fromUtf8("sdpStatusBar"))
        MainWindow.setStatusBar(self.sdpStatusBar)
        self.mplactionOpen = QtGui.QAction(MainWindow)
        self.mplactionOpen.setObjectName(_fromUtf8("mplactionOpen"))
        self.mplactionQuit = QtGui.QAction(MainWindow)
        self.mplactionQuit.setObjectName(_fromUtf8("mplactionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mplactionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Data Analysing", None, QtGui.QApplication.UnicodeUTF8))
        self.pickingModeCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.pickingModeCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "pan", None, QtGui.QApplication.UnicodeUTF8))
        self.pickingModeCombo.setItemText(2, QtGui.QApplication.translate("MainWindow", "kick", None, QtGui.QApplication.UnicodeUTF8))
        self.pickingModeCombo.setItemText(3, QtGui.QApplication.translate("MainWindow", "identify", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.avgStd.setText(QtGui.QApplication.translate("MainWindow", "Averaging with std", None, QtGui.QApplication.UnicodeUTF8))
        self.avgStdSqrtN.setText(QtGui.QApplication.translate("MainWindow", "Averaging with std/sqrt(N)", None, QtGui.QApplication.UnicodeUTF8))
        self.axesGroup.setTitle(QtGui.QApplication.translate("MainWindow", "axes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Fit-Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "x1 =", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "x2 =", None, QtGui.QApplication.UnicodeUTF8))
        self.updateFitRangeButton.setText(QtGui.QApplication.translate("MainWindow", "Update fitrange", None, QtGui.QApplication.UnicodeUTF8))
        self.fittingParametersGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.fillAutoFitParametersButton.setText(QtGui.QApplication.translate("MainWindow", "Reset to recommended initial parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Transform-Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Axes Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "x-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.resetAxisStyleButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.applyAxisStyleButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Axes Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "x-min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "y-min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "x-max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "y-max", None, QtGui.QApplication.UnicodeUTF8))
        self.resetRangeButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRangeButton.setText(QtGui.QApplication.translate("MainWindow", "Fix range", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Plot Style", None, QtGui.QApplication.UnicodeUTF8))
        self.plotStyleListLinePlot.setText(QtGui.QApplication.translate("MainWindow", "ListLinePlot", None, QtGui.QApplication.UnicodeUTF8))
        self.plotStyleListPlot.setText(QtGui.QApplication.translate("MainWindow", "ListPlot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Standard infos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Holdingtime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Trap parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Ramping time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Compressed Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Calibration resonance", None, QtGui.QApplication.UnicodeUTF8))
        self.infoCopyEdit.setText(QtGui.QApplication.translate("MainWindow", "Copy as text", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.fitDataButton.setText(QtGui.QApplication.translate("MainWindow", "Fit data", None, QtGui.QApplication.UnicodeUTF8))
        self.averageDataButton.setText(QtGui.QApplication.translate("MainWindow", "Average data", None, QtGui.QApplication.UnicodeUTF8))
        self.transformDataButton.setText(QtGui.QApplication.translate("MainWindow", "Transform data", None, QtGui.QApplication.UnicodeUTF8))
        self.clipboardPlotButton.setText(QtGui.QApplication.translate("MainWindow", "Copy plot to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.clipboardDataButton.setText(QtGui.QApplication.translate("MainWindow", "Copy data to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.exportDataButton.setText(QtGui.QApplication.translate("MainWindow", "Export data", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionOpen.setText(QtGui.QApplication.translate("MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

import PyQt4.QtGui
from PyQt4.Qwt5 import QwtPlot
from PyQt4.Qwt5 import QwtThermo
import PyQt4.Qwt5 as Qwt5
import icons.main_rc

